name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    types: [ opened, synchronize ]
  workflow_dispatch:

jobs:
  build-lint-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu' # See 'Supported distributions' for available options
          java-version: '17'
          cache: gradle

      - name: Load secret keys
        env:
          FIREBASE_CLIENT_ID: ${{ secrets.FIREBASE_CLIENT_ID }}
        run: echo FIREBASE_CLIENT_ID="$FIREBASE_CLIENT_ID" > ./local.properties

      - name: Run lint
        run: ./gradlew lintDebug
      - name: Upload lint html report
        uses: actions/upload-artifact@v2
        with:
          name: lint.html
          path: app/build/reports/lint-results-debug.html

      - name: Run unit tests
        run: ./gradlew test
      - name: Upload test report
        uses: actions/upload-artifact@v2
        with:
          name: unit_test_report
          path: app/build/reports/tests/testDeb